repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
-   repo: https://gitlab.com/daverona/pre-commit/cpp
    rev: 0.8.0
    hooks:
    -   id: clang-format
        args: ["-style=Google"]
    -   id: cpplint
        args: ["--filter=-legal/copyright,-build/include_order"]
    -   id: cppcheck
        args: ["--inline-suppr", "--library=boost"]
